name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # یہ سٹیپ اس کرپٹڈ فائل کو ڈیلیٹ کر دے گا تاکہ گٹ ہب کا سیکیورٹی چیک اسے بلاک نہ کرے
    - name: Delete corrupted wrapper
      run: rm -rf gradle/wrapper/

    # اب یہ بالکل آفیشل اور فریش گریڈل ڈاؤن لوڈ کرے گا
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 9.3.1

    - name: Generate dummy debug keystore
      run: keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"

    - name: Build Debug APK
      run: gradle assembleDebug

    - name: Upload all APKs
      uses: actions/upload-artifact@v4
      with:
        name: Anu-Battle-APK
        path: '**/*.apk'
